import { Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { SiteLayout } from '@/components/site/SiteLayout';

const faqs = [
  ['Quem pode adquirir imóveis Caixa?', 'Podem participar pessoas físicas maiores de 18 anos; maiores de 16 e menores de 18 anos, quando emancipadas; e pessoas jurídicas estabelecidas no território nacional, por meio de seus representantes legais. Devem ser observados os impedimentos dos editais e das regras da modalidade.'],
  ['Que tipos de imóveis estão à venda?', 'São imóveis usados de propriedade da Caixa, como casas, apartamentos, salas comerciais, glebas e terrenos, disponíveis com preços atrativos e condições específicas.'],
  ['Quais são as formas de pagamento?', 'Cada imóvel possui condições próprias, que podem incluir pagamento à vista, financiamento pela Caixa, uso do FGTS ou parcelamento. A condição aplicável consta na página do imóvel e no edital.'],
  ['O que preciso fazer após adquirir um imóvel Caixa?', 'Após a compra, o adquirente deve comparecer ao Cartório de Registro de Imóveis e realizar o registro da propriedade por meio da escritura ou do contrato de compra e venda. A partir do registro, passa a ser o titular do direito real do imóvel.'],
  ['O que preciso fazer quando comprar um imóvel ocupado?', 'A desocupação é de responsabilidade do comprador. Caso não ocorra de forma amigável, pode ser necessária ação judicial, sendo recomendável buscar orientação jurídica antes da compra.'],
  ['Os imóveis podem ser visitados?', 'Não existe previsão de disponibilização de chaves para visitação. Quando o imóvel estiver desocupado, localizado em condomínio e a chave estiver com o administrador, o contato deverá ser feito com o condomínio para verificar a possibilidade de entrada.'],
  ['A descrição e as fotos refletem a situação atual?', 'A descrição, as fotos e as áreas são enunciativas e podem não refletir a situação atual. Os dados são obtidos em laudos realizados anteriormente. Os imóveis são vendidos no estado de ocupação e conservação em que se encontram, cabendo ao comprador os ônus de eventuais reformas e regularizações, conforme o caso.'],
  ['Por que um imóvel que eu acompanhava não está mais no site?', 'O imóvel pode ter sido vendido, retirado temporariamente para correção de informações, estar com demanda tecnológica ou ter a venda suspensa por ordem judicial.'],
  ['Como comprar um imóvel Caixa?', 'Na Venda Online e na Venda Direta Online, as propostas são feitas na página oficial do imóvel. O interessado informa sua oferta conforme os campos e condições indicados pela Caixa. Nossa equipe pode orientar você durante esse processo.'],
  ['Como funciona a disputa na Venda Online?', 'O imóvel fica disponível para propostas durante o período indicado. Podem ser recebidas propostas enquanto o cronômetro não chega a zero. Novas propostas nos minutos finais podem prorrogar o prazo, conforme as regras vigentes. A Caixa analisa e homologa a proposta vencedora.'],
  ['Existe valor mínimo para a entrada?', 'Como sinal, a Caixa exige pelo menos 5% do valor mínimo de venda no prazo indicado após a homologação. Para empregados Caixa, a entrada pode ser dispensada quando houver financiamento integral e crédito aprovado. Cada caso depende da análise e das regras do edital.'],
  ['É possível comprar usando o FGTS?', 'Sim. O FGTS pode ser utilizado quando o imóvel, a operação e o comprador atendem às condições legais vigentes.'],
  ['Quais custos terei ao adquirir o imóvel?', 'Há custos tradicionais como escritura ou contrato, certidões, registro e ITBI. A responsabilidade por IPTU, condomínio e outras despesas depende da modalidade, do edital e da situação do imóvel.'],
  ['Preciso pagar a imobiliária ou o corretor credenciado?', 'Não. Quando houver comissão de venda, ela é paga pela Caixa. Modalidades como leilão ou licitação aberta podem ter comissão de leiloeiro paga pelo comprador, conforme o edital.'],
];

export default function SiteFaq() {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => faqs.filter(([q, a]) => `${q} ${a}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <SiteLayout title="Perguntas frequentes" description="Respostas sobre imóveis Caixa, financiamento, entrada, FGTS, propostas e documentação.">
    <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-4xl px-4 py-14 text-center sm:px-6"><p className="text-xs font-bold uppercase text-accent">Central de ajuda</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Como podemos ajudar?</h1><p className="mx-auto mt-4 max-w-2xl text-primary-foreground/75">Respostas claras para as principais dúvidas sobre a compra de imóveis Caixa.</p><label className="relative mx-auto mt-8 block max-w-2xl"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Busque por entrada, FGTS, visita…" className="h-14 w-full rounded-lg border-0 bg-background pl-12 pr-4 text-foreground shadow-xl outline-none focus:ring-2 focus:ring-accent" /></label></div></section>
    <section className="mx-auto max-w-4xl px-4 py-12 sm:px-6">{filtered.length ? <Accordion type="single" collapsible className="space-y-3">{filtered.map(([question, answer], index) => <AccordionItem key={question} value={`item-${index}`} className="rounded-lg border border-border bg-card px-5"><AccordionTrigger className="text-left text-base font-bold text-foreground hover:no-underline">{question}</AccordionTrigger><AccordionContent className="pr-8 text-sm leading-7 text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion> : <div className="py-16 text-center"><p className="font-bold text-foreground">Nenhuma resposta encontrada</p><p className="mt-1 text-sm text-muted-foreground">Tente buscar por outra palavra.</p></div>}<p className="mt-8 text-xs leading-5 text-muted-foreground">As condições podem variar conforme o imóvel, a modalidade, o edital e as regras vigentes da Caixa. Consulte os documentos oficiais antes de fazer uma proposta.</p></section>
  </SiteLayout>;
}